#!/usr/bin/python3
# COMP3311 20T3 Ass3 ... get Name's biography/filmography

import sys
import psycopg2
#from helpers import whatever, functions, you, need
from helpers import printnameandbirth,checkargv,checkyear
# define any local helper functions here

# set up some globals

usage = "Usage: bio 'NamePattern' [Year]"
db = None

# process command-line args

argc = len(sys.argv)
checkargv(argc,usage)
if argc == 3:
  year = sys.argv[2]
  checkyear(year,usage)
  
name = sys.argv[1]
# manipulate database

try:
  db = psycopg2.connect("dbname=imdb")
  cur = db.cursor()
  if argc == 3: 
    qry = "select name,birth_year,death_year,id from Names where name ~* %s and birth_year = %s order by name,birth_year,id"
    cur.execute(qry,[name,year])
  else:
    qry = "select name,birth_year,death_year,id from Names where name ~* %s order by name,birth_year,id"
    cur.execute(qry,[name])
  result = cur.fetchall()
  if(len(result) == 0):
    # cannot find person
    print(f'No name matching \'{name}\'')
  elif len(result) == 1:
    # find one! print the name and prin movie!
    target = result[0]
    print('Filmography for ' + printnameandbirth(target))
    nameid = target[3]
    print('===============')
    # find all movies this perple prin in
    qry = '''
    select title,start_year,id
    from Movies mov
    inner join Principals pr on pr.movie_id = mov.id
    where pr.name_id = %s
    group by title,start_year,id
    order by start_year,title
    '''
    cur.execute(qry,[nameid])
    movierresult = cur.fetchall()
    for movie in movierresult:
      print(f'{movie[0]} ({movie[1]})')
      moveid = movie[2]
      #act 
      actqry = '''
      select played
      from Acting_roles
      where Acting_roles.name_id = %s and Acting_roles.movie_id = %s
      order by played
      '''
      cur.execute(actqry,[nameid,moveid])
      actresult = cur.fetchall()
      for act in actresult:
        print(f' playing {act[0]}')
      #crew
      crewqry = '''
      select role
      from Crew_roles
      where Crew_roles.name_id = %s and Crew_roles.movie_id = %s
      order by role
      '''
      cur.execute(crewqry,[nameid,moveid])
      crewresult = cur.fetchall()
      for crew in crewresult:
        word = crew[0].replace('_',' ').capitalize()
        print(f' as {word}')

  else:
    # find mulip people
    print(f'Names matching \'{name}\'')
    print('===============')
    for name in result:
      print(printnameandbirth(name))
    
      
      
except psycopg2.Error as err:
  print("DB error: ", err)
finally:
  if db:
    db.close()

