#!/usr/bin/python3
# COMP3311 20T3 Ass3 ... print info about cast and crew for Movie

import sys
import psycopg2
#from helpers import whatever, functions, you, need
from helpers import checkargv,checkyear
# define any local helper functions here

# set up some globals

usage = "Usage: minfo 'MovieTitlePattern' [Year]"
db = None

# process command-line args

argc = len(sys.argv)
checkargv(argc,usage)
if argc == 3:
  year = sys.argv[2]
  checkyear(year,usage)
  
name = sys.argv[1]
# manipulate database


try:

  db = psycopg2.connect("dbname=imdb")
  cur = db.cursor()
  if argc == 3: 
    qry = "select title,start_year,id from movies where title ~* %s and start_year = %s   order by start_year,title"
    cur.execute(qry,[name,year])
  else:
    qry = "select title,start_year,id from movies where title ~* %s order by start_year,title"
    cur.execute(qry,[name])
  result = cur.fetchall()
  if(len(result) == 0):
    # not find movie
    if argc == 3:
      print(f'No movie matching \'{name}\' {year}')
    else:
      print(f'No movie matching \'{name}\'')
  elif len(result) == 1:
    # find movie! print act and crew list
    print(f'{result[0][0]} ({result[0][1]})')
    print('===============')
    print('Starring')
    # search act 
    actqry = '''
    select Names.name, Acting_roles.played 
    from Acting_roles 
    inner join Names on Acting_roles.name_id = Names.id
    inner join Principals on Principals.name_id = Acting_roles.name_id and Principals.movie_id = Acting_roles.movie_id
    where Acting_roles.movie_id = %s
    order by Principals.ordering, Names.name'''
    cur.execute(actqry,[result[0][2]])
    actorresult = cur.fetchall()
    for act in actorresult:
      print(f' {act[0]} as {act[1]}')
    print('and with')
    # search crew 
    crewqry = '''
    select Names.name, Crew_roles.role 
    from Crew_roles 
    inner join Names on Crew_roles.name_id = Names.id
    inner join Principals on Principals.name_id = Names.id and Principals.movie_id = Crew_roles.movie_id
    where Crew_roles.movie_id = %s
    group by Names.name, Crew_roles.role,Principals.ordering
    order by Principals.ordering, Names.name'''
    cur.execute(crewqry,[result[0][2]])
    crewresult = cur.fetchall()
    for crew in crewresult:
      word = crew[1].replace('_',' ').capitalize()
      print(f' {crew[0]}: {word}')
  else:
    # find mutilp movies, print all movies
    if argc == 3:
      print(f'Movies matching \'{name}\' {year}')
    else:
      print(f'Movies matching \'{name}\'')
    print('===============')
    for movie in result:
      print(f'{movie[0]} ({movie[1]})')

except psycopg2.Error as err:
  print("DB error: ", err)
finally:
  if db:
    db.close()

